const countries = [
    "Russia",
    "Canada",
    "United States",
    "China",
    "Brazil",
    "Australia",
    "India",
    "Argentina",
    "Kazakhstan",
    "Algeria",
    "DR Congo",
    "Greenland",
    "Saudi Arabia",
    "Mexico",
    "Indonesia",
    "Sudan",
    "Libya",
    "Chad",
    "Niger",
    "Angola",
    "Mali",
    "South Africa",
    "Colombia",
    "Ethiopia",
    "Bolivia",
    "Mauritania",
    "Egypt",
    "Tanzania",
    "Nigeria",
    "Venezuela",
    "Pakistan",
    "Turkey",
    "Chile",
    "Zambia",
    "Myanmar",
    "Afghanistan",
    "Somalia",
    "Central African Republic",
    "Ukraine",
    "Madagascar",
    "Botswana",
    "Kenya",
    "Yemen",
    "Thailand",
    "Spain",
    "Turkmenistan",
    "Cameroon",
    "Papua New Guinea",
    "Albania",
    "Andorra",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Georgia",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Kosovo",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Moldova",
    "Montenegro",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Switzerland",
    "Ukraine",
    "United Kingdom",
    "Fiji",
    "Kiribati",
    "Marshall Islands",
    "Micronesia",
    "Nauru",
    "New Zealand",
    "Palau",
    "Samoa",
    "Solomon Islands",
    "Tonga",
    "Tuvalu",
    "Vanuatu",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cape Verde",
    "Comoros",
    "Congo",
    "Cote d'Ivoire",
    "Djibouti",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Lesotho",
    "Liberia",
    "Mauritius",
    "Morocco",
    "Namibia",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Sudan",
    "Togo",
    "Tunisia",
    "Uganda",
    "Western Sahara",
    "Zambia",
    "Zimbabwe",
    "Antigua and Barbuda",
    "Aruba",
    "Bahamas",
    "Barbados",
    "Belize",
    "Bermuda",
    "Costa Rica",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "El Salvador",
    "Grenada",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Jamaica",
    "Panama",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Trinidad and Tobago",
    "Turks and Caicos Islands",
    "Puerto Rico"
];

const countryListElement = document.getElementById('countryList');

countries.forEach(country => {
    const listItem = document.createElement('li');
    listItem.textContent = country;
    countryListElement.appendChild(listItem);
});
